models:
  - type: main
    engine: nvidia_ai_endpoints
    model: meta/llama3-8b-instruct

prompts:
  - role: user
    content: |
      {{rail_context}}
      {{user_message}}
  - role: assistant
    content: |
      {{agent_response}}

rails:
  # Input rails are invoked when new input from the user is received.
  input:
    flows:
      - check jailbreak
      - mask sensitive data on input

  # Output rails are triggered after a bot message has been generated.
  output:
    flows:
      - self check facts
      - self check hallucination
      - activefence moderation
      - gotitai rag truthcheck

  config:
    # Configure the types of entities that should be masked on user input.
    sensitive_data_detection:
      input:
        entities:
          - PERSON
          - EMAIL_ADDRESS
